[package]
name = "move"
version = "1.0.0"
authors = []

[addresses]
my_addr="903f9346940a83dac717774850def813aea9558de6e2301b060a5b9460bb8c98"
[dev-addresses]


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
